# site properties and page defaults
title: CGKlab
subtitle: STRESS & ADDICTION RESEARCH
description: The goal of the CGKlab is to identify the neurological mechanisms that underlie stress-induced vulnerability in the development of substance use disorders, and in doing so, rationally design pharmacotherapeutic treatments. The lab uses a preclinical rodent model to understand how an acute stressful event can lead to addiction, not only facilitating drug self-administration but also precipitating relapse.
header: images/background.jpg
footer: images/background.jpg
proofer: false
logo-text: false

# site social media and other links
links:
  email:  CGKLab@mcw.edu
  #orcid: 0000-0001-8713-9213
  #google-scholar: ETJoidYAAAAJ
  github: CGK-Laboratory
  #linkedin: constanza-garcia-keller
  twitter: cgarciakeller
  instagram: cgklab
### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts
  - robots.txt

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
